version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267348520.dkr.ecr.us-east-1.amazonaws.com
  build: 
    commands: 
      - docker build -t web .
      - docker tag web:latest 533267348520.dkr.ecr.us-east-1.amazonaws.com/web:latest

  post_build:
    commands:
      - docker push 533267348520.dkr.ecr.us-east-1.amazonaws.com/web:latest
